### ISSUE TITLE
getUser method returns null

### ISSUE THREAD

**Issue by Truemedia** [skipperbent/tinder-php-sdk#7]
Hi there,
I have installed this package and am trying to call the first API method document in your README getUser.

I have read through the facebook developer docs and have provided a user ID which matches up to the user I am logging in with for facebook developer area (also tried App ID). The token I used was from the client token facebook has listed on my app management page.

Passing in the parameters always gives me null, and I'm not sure how to find out what the problem is.

Would appreciate any help or advice on debugging.

**Comment by skipperbent** [comment]
Hi there,

It's a paint figuring out how to get it working with the Facebook tokens etc. 

I'll just try it out myself and see if I can get the `getUser` method working and report back. It's been a while since i've used the SDK, so it might need some updating.
- Simon

**Comment by skipperbent** [comment]
Hi again, i've just tried and got the user information in first try, so it's definitely working.

http://screencast.com/t/1y9LQSPiIM

Make sure that you are using the correct Facebook user id and auth-token:
https://github.com/skipperbent/tinder-php-sdk

See "Getting your Facebook token".

I've updated the documentation to show a simple way of obtaining the Facebook auth token. You can use a service like http://findmyfbid.com/ to find your Facebook user id.

Please let me know if this sorted out your issue, otherwise i'll be happy to assist you further.

\- Simon

**Comment by Truemedia** [comment]
Cheers for the quick response :+1: 

Yeh turns out it was my auth token, I tried getting that from an alternative source and misread the fact that the page you provided you have to be quick with the copy and paste.

It's now working just trying to get my head round the methods available.

I will close this issue thanks.
